#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ainsl /etc/sysctl.conf vm.nr_hugepages=12
ainsl /etc/sysctl.conf vkernel.nmi_watchdog=0
ainsl /etc/sysctl.conf vkernel.sched_rt_runtime_us=-1
