#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Disable systemd's network interface name management.
# References:
#   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863385
#   https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

$ROOTCMD touch /etc/modprobe.d/qemu-system-x86.conf
ainsl /etc/modprobe.d/qemu-system-x86.conf "options kvm_intel nested=1 enable_apicv=n ple_gap=0 ple_window=0"
ainsl /etc/modprobe.d/qemu-system-x86.conf "options vhost_net experimental_zcopytx=1"
