#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -m root,root,0755 /usr/local/sbin/cache_allocator.sh
fcopy -M /etc/systemd/system/cache-allocator.service
$ROOTCMD ln -s /etc/systemd/system/cache-allocator.service /etc/systemd/system/multi-user.target.wants/cache-allocator.service
